kind: Service
apiVersion: v1
metadata:
  name: etcd-traefik-store
  namespace: kube-system
spec:
  selector:
    etcd_cluster: etcd-traefik-store
    app: etcd
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
  type: ClusterIP
